### ISSUE TITLE
Cannot read property 'knexSchema' of undefined

### ISSUE THREAD

**Issue by optii** [BigRoomStudios/schwifty-migrate-diff#12]
Getting this error when trying to run the migration from zero (nothing in db & no previous migrations)

Stacktrace:

```
/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'knexSchema' of undefined
    at String.handlebars.registerHelper (/node_modules/schwifty-migrate-diff/lib/index.js:788:19)
    at eval (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:173)
    at prog (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at String.<anonymous> (/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:31)
    at prog (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:34)
    at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as build-table-create-list] (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at Object.eval [as main] (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
```

I can provide the models if needed

**Comment by wswoodruff** [comment]
@optii 🤔Thank you for posting this issue -- I wonder if the existence of the tables is required -- What you're doing is definitely a major use-case (seed the db with tables / correct columns and types!)

**Comment by optii** [comment]
So this seems to stem from a `joi` schema that has a key named `email` in it:

## Doesnt work:
```javascript
Joi.object({
   email: Joi.string().email()
})
```

## Does work:
```javascript
Joi.object({
   test: Joi.string().email()
})
```

**Comment by optii** [comment]
Update to this, the key `email` has nothing to do with it, this case seems to occur whenever a key is identical to the table name.

For example this will fail:

```javascript
class Email extends Model {
   
   static get tableNamee() {
        return 'email';
   }

   static get joiSchema(){
        return Joi.object({ email: Joi.string().email() });
   }
}
```

**Comment by wswoodruff** [comment]
Confirmed that this is reproducible ^^^

**Comment by optii** [comment]
Done some debugging concerning this, all the generated objects seem to be correct and seem to have boiled down the problem to a context problem in the handlebars template, here is what i've "found":

I've run my tests against the `Dog` model that i added the key `Dog` to.

[line 1](https://github.com/BigRoomStudios/schwifty-migrate-diff/blob/d8ca5b4c5aca3e6f2e7e3186da11a685a114b60b/lib/hbs/partials/build-table-create-list.hbs#L1) evaluates to `['Dog']` which seems correct to me

`this` context in the first `{{#each }}` (above) evalutes to `'Dog'` as expected

[line 4](https://github.com/BigRoomStudios/schwifty-migrate-diff/blob/d8ca5b4c5aca3e6f2e7e3186da11a685a114b60b/lib/hbs/partials/build-table-create-list.hbs#L4) evaluates to `[ 'id', 'favoriteToy', 'name', 'Dog', 'ownerId' ]` again this seems good to me

in this `{{#each }}` however things seem break: 

  - `this` equals the correct values on each iteration. in order `'id'` `'favoriteToy'` `'name'` `'Dog'` `'ownerId'` (again this looks good)
  - `../this` evaluates to `Dog` for each of the values except for when `this` equals `Dog` and in this case `../this` evaluates to the `@root` object instead of `Dog`

I can't seem to work out why when `this` equals `Dog` the parent this is changed. I'm going to keep looking into this but if you've got any ideas :+1:

**Comment by optii** [comment]
Okay seem to have a fix for this, maybe it's due to a circular reference ? I'll create a PR
